CREATE TABLE STANOWISKO(idSTANOWISKO INT AUTO_INCREMENT PRIMARY KEY, nazwa_STANOWISKA VARCHAR(45));
CREATE TABLE PENSJA(idPENSJA INT AUTO_INCREMENT PRIMARY KEY, STANOWISKO_idSTANOWISKA INT NOT NULL, ILOSC FLOAT NOT NULL, FOREIGN KEY(STANOWISKO_idSTANOWISKA) REFERENCES STANOWISKO(idSTANOWISKO));
CREATE TABLE REKLAMA(idREKLAMA INT AUTO_INCREMENT PRIMARY KEY, TYP_REKLAMY VARCHAR(45) NOT NULL, nazwa_reklamy VARCHAR(50) NOT NULL, CENA FLOAT NOT NULL, DEADLINE DATE);
CREATE TABLE KLIENT(idKLIENT INT AUTO_INCREMENT PRIMARY KEY, IMIE VARCHAR(30) NOT NULL, NAZWISKO VARCHAR(35) NOT NULL, NAZWA_FIRMY VARCHAR(70) NOT NULL, ZAMOWIENIE INT(10) NOT NULL);
CREATE TABLE PRACOWNIK(idPRACOWNIK INT AUTO_INCREMENT PRIMARY KEY, IMIE VARCHAR(30) NOT NULL, NAZWISKO VARCHAR(35) NOT NULL, NUMER_KONTA VARCHAR(26) NOT NULL, PENSJA_idPENSJA INT NOT NULL, ADRES VARCHAR(70) NOT NULL, STANOWISKO_idSTANOWISKO INT NOT NULL, FOREIGN KEY(PENSJA_idPENSJA) REFERENCES PENSJA(idPENSJA), FOREIGN KEY(STANOWISKO_idSTANOWISKO) REFERENCES STANOWISKO(idSTANOWISKO));
CREATE TABLE USLUGI(idUSLUGI INT AUTO_INCREMENT PRIMARY KEY, REKLAMA_idREKLAMA INT NOT NULL, FOREIGN KEY(REKLAMA_idREKLAMA) REFERENCES REKLAMA(idREKLAMA));
CREATE TABLE DZIAL_REKLAMY_ZAMOWIENIA(idDZIAL_REKLAMY_ZAMOWIENIA INT(15) AUTO_INCREMENT PRIMARY KEY, USLUGI_idUSLUGI INT NOT NULL, KLIENT_idKLIENT INT NOT NULL, PRACOWNIK_idPRACOWNIK INT NOT NULL, FOREIGN KEY(USLUGI_idUSLUGI) REFERENCES USLUGI(idUSLUGI), FOREIGN KEY(KLIENT_idKLIENT) REFERENCES KLIENT(idKLIENT), FOREIGN KEY(PRACOWNIK_idPRACOWNIK) REFERENCES PRACOWNIK(idPRACOWNIK));

DELIMITER $$
CREATE PROCEDURE NOWE_ZAMOWIENIE (IN USLUGA INT, KLIENT INT, PRACOWNIK INT)
BEGIN 
INSERT INTO DZIAL_REKLAMY_ZAMOWIENIA VALUES(default, USLUGA, KLIENT, PRACOWNIK);
END $$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION zamowienie(id INT)
RETURNS VARCHAR(255)
BEGIN
DECLARE tekst VARCHAR(255);
SELECT CONCAT('Zamowienie: ',id, ' ',r.TYP_REKLAMY,' ',r.nazwa_reklamy, ' Klient: ', k.IMIE,' ',k.NAZWISKO,' Pracownik: ',p.IMIE,' ',p.NAZWISKO) INTO @tekst FROM DZIAL_REKLAMY_ZAMOWIENIA d JOIN USLUGI u ON u.idUSLUGI=d.USLUGI_idUSLUGI JOIN REKLAMA r ON r.idREKLAMA=u.REKLAMA_idREKLAMA JOIN KLIENT k ON k.idKLIENT=d.KLIENT_idKLIENT JOIN PRACOWNIK p ON p.idPRACOWNIK=d.PRACOWNIK_idPRACOWNIK WHERE id=d.idDZIAL_REKLAMY_ZAMOWIENIA;
RETURN @tekst;
END
$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER zla_pensja 
BEFORE INSERT ON PENSJA
FOR EACH ROW
BEGIN 
IF NEW.ILOSC <2500
THEN 
SET NEW.ILOSC = 2500;
END IF ;
END $$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER AWANS 
BEFORE UPDATE ON PRACOWNIK
FOR EACH ROW
BEGIN
IF NEW.STANOWISKO_idSTANOWISKO!= OLD.STANOWISKO_idSTANOWISKO
THEN 
SET NEW.PENSJA_idPENSJA=NEW.STANOWISKO_idSTANOWISKO;
END IF;
END $$
DELIMITER ;

